### ISSUE TITLE
代码太复杂了  有没有教程啊

### ISSUE THREAD

**Issue by kilcer** [fallingrust/GB28181Client#1]

**Comment by fallingrust** [comment]
GB28181文件夹的代码用的是开源的不需要看（tools/psmuxer 除外），除非需要改东西，基本就是拼接字符串，看下service就行。

**Comment by kilcer** [comment]
可是我在接受到查看视频的Invite时没有y= 这个  所以String y= body.substring(body.indexOf("y=")+2,body.indexOf("y=")+12);会报错

**Comment by kilcer** [comment]
请问开源的那个资料有吗？我想学习一下

**Comment by fallingrust** [comment]
收到的sdp你用sdpParse转换，我这个只是测试用的；资料的话你搜下Sipdroid你这开源库，网上有不少

**Comment by kilcer** [comment]
好的，多谢大哥
