### ISSUE TITLE
后续会考虑加入音频传输吗

### ISSUE THREAD

**Issue by anyan131** [fallingrust/GB28181Client#10]
后续会考虑加入音频传输吗

**Comment by fallingrust** [comment]
暂时没有哎，这个方案被公司pass了，所以只能是Demo状态了。而且使用java实现国标不是最优解，最好还是用c/c++之类的开发库，手机、嵌入式设备都能用。

**Comment by anyan131** [comment]
您那有比较推荐的jni库可以供安卓端使用的吗，或者有可以参考的吗

**Comment by fallingrust** [comment]
应该没有吧，估计得自己封装
