### ISSUE TITLE
视频会卡  然后一下又很快播放，平台录制出来的视频有59FPS

### ISSUE THREAD

**Issue by kilcer** [fallingrust/GB28181Client#2]
视频会卡  然后一下又很快播放，平台录制出来的视频有59FPS，不知道这个测试过没有  我尝试修改但是感觉没用

**Comment by fallingrust** [comment]
没有测过录制，只是简单看下播放，在SRS livegbs这两个平台看过，效果还好。修改的话，看下发送数据包部分，可能是因为时间戳的问题导致的。代码只是用来测试功能的，仅供参考。
