### ISSUE TITLE
密码校验通不过

### ISSUE THREAD

**Issue by madzheng** [fallingrust/GB28181Client#3]
GB28181Client和sip服务器设置相同的密码，但是向sip服务器注册的时候sip服务器提示密码校验通不过，也注册不上。请问这是什么原因？

**Comment by fallingrust** [comment]
这个我没遇到过，这个代码只是测试用的，建议用海康等标准国标设备进行抓包看下

**Comment by madzheng** [comment]
想进一步请教一下，不知道方不方便加个微信。我的微信号是：maxlee2931
