### ISSUE TITLE
密码校验

### ISSUE THREAD

**Issue by tanghubin** [fallingrust/GB28181Client#6]
DigestAuthentication 代码里有一段 判断 qop!=null 这里有点问题，如果没有收到qop字段信息，会被初始化为字符串的null,"null"，所以永远都不会为null，这里会影响到密码校验

**Comment by fallingrust** [comment]
这块代码用的是SipDroid一个开源的SIP库，这个项目是个Demo,因为SIP过于臃肿，所以这个方案被Pass了

**Comment by tanghubin** [comment]
那你们目前是怎么做的呢，方便参考一下这一块儿的代码吗？

**Comment by fallingrust** [comment]
用MQTT做信令传输，设备端采用类似腾讯云物模型设计。有级联需求的话，就平台之间级联，而不是设备接入其他平台。
