### ISSUE TITLE
service里 获取y值 角标越界问题

### ISSUE THREAD

**Issue by tanghubin** [fallingrust/GB28181Client#7]
service里 获取y值 角标越界问题
测试中有的平台返回的y值为0 如果固定写死+12获取y值 会有角标越界的风险，建议判断+12后是否超出长度，或者以长度为endIndex 来获取y值

**Comment by tanghubin** [comment]
另外 我想问一下 项目里只有udp推流，如果用tcp推流怎么实现呢，能大概介绍一下吗，编码这一块了解的不多

**Comment by fallingrust** [comment]
当时只用了一个LiveGBS平台来测试，可能测试不充分; 关于RTP封包的你可以看下这个文章https://blog.csdn.net/ichenwin/article/details/100086930，TCP推流的话，搜下RTP over tcp 文章还是很多的；有海康摄像头的话抓个包，分析下，问题应该不大的
