### ISSUE TITLE
初始化摄像头读取数据推流时报错，SDK 19，请问如何解决呢？

### ISSUE THREAD

**Issue by xiaohuangtongxue** [fallingrust/GB28181Client#8]
![image](https://user-images.githubusercontent.com/15182754/218248677-16eed440-8df1-4579-8266-31b0434ce3d5.png)

**Comment by freedomcain** [comment]
> ![image](https://user-images.githubusercontent.com/15182754/218248677-16eed440-8df1-4579-8266-31b0434ce3d5.png)

您好，请问还有研究这个例子吗？能否留个联系方式指导一下，谢谢。

**Comment by lhf-Alice** [comment]
> > ![image](https://user-images.githubusercontent.com/15182754/218248677-16eed440-8df1-4579-8266-31b0434ce3d5.png)
> 
> 您好，请问还有研究这个例子吗？能否留个联系方式指导一下，谢谢。
编码不对

**Comment by fallingrust** [comment]
如果硬件编码器不支持的话，建议集成ffmpeg，使用ffmpeg软编码
