### ISSUE TITLE
请教例程传输卡顿和图像翻转问题

### ISSUE THREAD

**Issue by freedomcain** [fallingrust/GB28181Client#9]
您好，使用了该例子测试，发现视频流传输过程中会出现卡顿，平台图像显示的画面是翻转了90度的，能否留个方式指导一下，实在是没什么头绪。

**Comment by fallingrust** [comment]
这边没在使用国标连接平台了，卡顿的话可能是视频分包发送需要优化（之前只是简单验证下可行性，没有持续优化，后来改方案了），旋转的话，可以集成libyuv来做效率比较高

**Comment by freedomcain** [comment]
> 

非常感谢回复，这段时间刚入门GB28181，目前使用这个例子基本可以满足在平台的显示。至于您说的视频分包部分需要优化，能否给点思路呢？是每次send(packet)之前需要增加延时吗，还是send之前对包做额外处理？另外看到gb28181_make_ps_header函数里面有提到一段话
![image](https://user-images.githubusercontent.com/23326282/226834176-a6387b9e-7649-4757-9693-40a0077905fd.png)

是不是需要根据实际的图像分辨率，调整时间戳？实在不太明白，求指导谢谢

**Comment by fallingrust** [comment]
15555157471 加我微信吧

**Comment by freedomcain** [comment]
> 15555157471 加我微信吧

感谢，已加，麻烦通过一下
